// Command vacuous_tests reports Go test functions that cannot fail because
// their body (and every t.Run subtest they spawn) contains no assertion and
// never hands *testing.T to a helper.
//
// The list of known offenders lives in scripts/vacuous_tests_allowlist.txt.
// CI fails when a test that is not on that list cannot fail, so the debt can
// only shrink.
//
// Usage:
//
//	vacuous_tests [-dir DIR] [-allowlist FILE] [-update]
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// assertNames are *testing.T methods that make a test fail (or skip).
var assertNames = map[string]bool{
	"Error":   true,
	"Errorf":  true,
	"Fatal":   true,
	"Fatalf":  true,
	"Fail":    true,
	"FailNow": true,
	"Skip":    true,
	"Skipf":   true,
	"SkipNow": true,
}

// helperNames are *testing.T methods that neither assert nor prove anything
// on their own; a test that only calls these is still vacuous.
var helperOnlyNames = map[string]bool{
	"Helper":   true,
	"Cleanup":  true,
	"Setenv":   true,
	"TempDir":  true,
	"Deadline": true,
	"Name":     true,
	"Parallel": true,
}

func main() {
	dir := flag.String("dir", ".", "root directory to scan")
	allowlist := flag.String("allowlist", "scripts/vacuous_tests_allowlist.txt", "allowlist file")
	update := flag.Bool("update", false, "rewrite the allowlist instead of checking against it")
	flag.Parse()

	found, err := scan(*dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "vacuous_tests:", err)
		os.Exit(2)
	}

	if *update {
		if err := writeAllowlist(*allowlist, found); err != nil {
			fmt.Fprintln(os.Stderr, "vacuous_tests:", err)
			os.Exit(2)
		}
		fmt.Printf("vacuous_tests: wrote %d entries to %s\n", len(found), *allowlist)
		return
	}

	allowed, err := readAllowlist(*allowlist)
	if err != nil {
		fmt.Fprintln(os.Stderr, "vacuous_tests:", err)
		os.Exit(2)
	}

	var fresh []string
	for _, key := range found {
		if !allowed[key] {
			fresh = append(fresh, key)
		}
	}
	var stale []string
	for key := range allowed {
		if _, ok := lookup(found, key); !ok {
			stale = append(stale, key)
		}
	}
	sort.Strings(fresh)
	sort.Strings(stale)

	if len(stale) > 0 {
		fmt.Printf("vacuous_tests: %d allowlist entries no longer apply (remove them): %s\n",
			len(stale), strings.Join(stale, ", "))
	}
	if len(fresh) > 0 {
		fmt.Printf("vacuous_tests: %d test(s) cannot fail:\n", len(fresh))
		for _, key := range fresh {
			fmt.Println("  " + key)
		}
		fmt.Println("fix them (add a real assertion) or add them to " + *allowlist)
		os.Exit(1)
	}
	fmt.Printf("vacuous_tests: OK (%d known vacuous tests allowlisted, %d new)\n", len(allowed), 0)
}

func lookup(list []string, key string) (string, bool) {
	for _, k := range list {
		if k == key {
			return k, true
		}
	}
	return "", false
}

func readAllowlist(path string) (map[string]bool, error) {
	out := map[string]bool{}
	f, err := os.Open(path) // #nosec G304 -- path comes from -allowlist flag, not untrusted input
	if os.IsNotExist(err) {
		return out, nil
	}
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out[line] = true
	}
	return out, sc.Err()
}

func writeAllowlist(path string, keys []string) error {
	sorted := append([]string(nil), keys...)
	sort.Strings(sorted)
	var b strings.Builder
	b.WriteString("# Tests that currently cannot fail. Every entry is debt:\n")
	b.WriteString("# add a real assertion to the test and delete its line here.\n")
	b.WriteString("# Generated by: go run ./scripts/vacuous_tests -update\n")
	for _, k := range sorted {
		b.WriteString(k)
		b.WriteString("\n")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o600) // #nosec G306
}

func scan(root string) ([]string, error) {
	var keys []string
	fset := token.NewFileSet()
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "node_modules" || name == "vendor" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return nil // unparseable files are somebody else's problem
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || fn.Body == nil {
				continue
			}
			if !strings.HasPrefix(fn.Name.Name, "Test") {
				continue
			}
			if !takesTestingT(fn) {
				continue
			}
			if !asserted(fn.Body) {
				rel, rerr := filepath.Rel(root, path)
				if rerr != nil {
					rel = path
				}
				keys = append(keys, filepath.ToSlash(rel)+":"+fn.Name.Name)
			}
		}
		return nil
	})
	return keys, err
}

func takesTestingT(fn *ast.FuncDecl) bool {
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 1 {
		return false
	}
	field := fn.Type.Params.List[0]
	if len(field.Names) != 1 || field.Names[0].Name != "t" {
		return false
	}
	star, ok := field.Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	return ok && pkg.Name == "testing" && sel.Sel.Name == "T"
}

// asserted reports whether b can make the test fail, either directly or
// through a t.Run subtest that itself can fail.
func asserted(b *ast.BlockStmt) bool {
	if b == nil {
		return false
	}

	direct := false
	ast.Inspect(b, func(n ast.Node) bool {
		if direct {
			return false
		}
		if _, ok := n.(*ast.FuncLit); ok {
			// Subtests are evaluated separately below.
			return false
		}
		if isAssertCall(n) {
			direct = true
			return false
		}
		return true
	})
	if direct {
		return true
	}

	subtests := false
	ast.Inspect(b, func(n ast.Node) bool {
		if subtests {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok || !isTRun(call) || len(call.Args) != 2 {
			return true
		}
		lit, ok := call.Args[1].(*ast.FuncLit)
		if !ok {
			return true
		}
		if asserted(lit.Body) {
			subtests = true
			return false
		}
		return true
	})
	return subtests
}

func isTRun(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Run" {
		return false
	}
	id, ok := sel.X.(*ast.Ident)
	return ok && id.Name == "t"
}

func isAssertCall(n ast.Node) bool {
	call, ok := n.(*ast.CallExpr)
	if !ok {
		return false
	}

	// require.X(...), assert.X(...)
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if id, ok := sel.X.(*ast.Ident); ok && (id.Name == "require" || id.Name == "assert") {
			return true
		}
		// t.Error(...), t.Fatal(...), t.Skip(...)
		if id, ok := sel.X.(*ast.Ident); ok && id.Name == "t" {
			if assertNames[sel.Sel.Name] {
				return true
			}
			if helperOnlyNames[sel.Sel.Name] {
				return false
			}
		}
	}

	// helper(t, ...) / helper(t): handing the testing.T to a helper means the
	// helper decides whether the test passes.
	if len(call.Args) > 0 {
		if id, ok := call.Args[0].(*ast.Ident); ok && id.Name == "t" {
			return true
		}
	}
	return false
}
